### ISSUE TITLE
Improve overall developer experience with SOQL Builder

### ISSUE THREAD

**Issue by brahmajitammana** [forcedotcom/soql-tooling#128]
**Is your feature request related to a problem? Please describe.**
Not specific to particular but it is about in general experience. here are the quick notes from my point of view:

1. Editing SOQL query is not friendly in text editor - it keeps selecting the SOQL builder view - probably known already
2. Option to edit the query inside soql query instead of text editory
3. Shortcut to open the soql query editor from apex classes/triggers on selecting the query
4. Auto suggestions for fields and its related fields
5. Ability to navigate to record in salesforce app
6. Ability to edit and delete the record from soql builder results
7. Run the query against another org easily or have an option for it

**Describe the solution you'd like**
Nothing specific, but would like to have the best solution that improve developer experience

**Describe alternatives you've considered**
Nothing

**Additional context**
None

**Comment by smaddox-sf** [comment]
Hi @brahmajitammana - Thanks for trying SOQL Builder and giving us feedback!  We aim to keep 1 topic per issue to stay organized and have focused discussions.  I mapped most of these items to individual issues and we can continue the discussion on those:

1. Does #76 describe the scenario you’re experiencing?  If not, [can you open a new issue with more details](https://github.com/forcedotcom/soql-tooling/issues/new?assignees=&labels=&template=bug-report.md&title) on what you’re seeing so we can look into this?
2. #135 - _Option to edit the query inside soql query instead of text editory_ - Logged as #135.  We’ve added a quick toggle to let you swap between the text editor and the Builder.  Have you tried this?  Check it out and weigh in on #135 if you have more input.
    
    
![image](https://user-images.githubusercontent.com/59572234/106207740-18cca780-6177-11eb-993e-3a5318847bad.png)



3. #139 - _Shortcut to open the soql query editor from apex classes/triggers on selecting the query_ 
4. _Auto suggestions for fields and its related fields_ - Can you elaborate on this one?  I assume you are using the text editor and missing some code completion suggestions?  Can you be specific on which scenarios aren’t working for you?  We’ve been making recent updates, but do not have it for the entire language.   [Please open a new issue with specifics on this one.](https://github.com/forcedotcom/soql-tooling/issues/new?assignees=&labels=&template=feature-request.md&title=)
5. #127 - _Ability to navigate to record in salesforce app_ 
6. _Ability to edit and delete the record from soql builder results_ - This isn't a scenario we plan to enable from the Builder at this time.
7. _Run the query against another org easily or have an option for it_ - You can authenticate multiple orgs and then select a different org to use.  You can access the org picker by clicking the Org Alias name in the status back (highlighted with an arrow in the screenshot).  That lets you select a different Org or authorize a new one.

![image](https://user-images.githubusercontent.com/59572234/106208106-b45e1800-6177-11eb-9991-d7f28879c12a.png)

I'm going to close this issue so discussion can continue on the individual issues.
