### ISSUE TITLE
SOQL Language Server - SOQL Snippet Restriction

### ISSUE THREAD

**Issue by sfsholden** [forcedotcom/soql-tooling#228]
### Summary

SOQL Snippet is available as an auto-completion option in contexts where it should not be available.

### Steps To Reproduce:

1.  Type query `SELECT Title, COUNT(Name) FROM Contact GROUP BY ROLLUP ` in a .soql file.
1.  Run auto-completion with Ctr+Space.

The SOQL snippet is also available outside of the .soql file context (.cls, .trigger, etc.).

### Expected result

The SOQL Snippet should not be available as an auto-complete option.

### Actual result

SOQL Snippet is available for auto-completion for the query `SELECT Title, COUNT(Name) FROM Contact GROUP BY ROLLUP ` in a .soql file.
<img width="1509" alt="SOQL Snippet is available for above query" src="https://user-images.githubusercontent.com/45604118/67506876-1bbf1b00-f64b-11e9-9a68-f1f5bcf85d38.png">

SOQL Snippet is available for auto-completion within an Apex Class.
<img width="1509" alt="SOQL Snippet is available within an Apex Class" src="https://user-images.githubusercontent.com/45604118/67507144-97b96300-f64b-11e9-84bd-b5e95b6413c8.png">

**Comment by smaddox-sf** [comment]
This is fixed in the new SOQL language server.  It will eventually be added to the extension pack, but is a separate extension for now - https://marketplace.visualstudio.com/items?itemName=salesforce.salesforcedx-vscode-soql.  It is currently active for .soql files.  Future work will enable it for embedded SOQL in Apex as well.
